
export const sample_cards: any[] = [
    {
        cardName:"Angel's Feather",
        imageUrl:"/assets/cardImg/angel'sFeather.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Animate Artifact",
        imageUrl:"/assets/cardImg/animateArtifact.jpg",
        convertedManaCost:4,
        type:['Enchantment'],
        subtype:['Aura'],
        cost:[['X', 1], ['Grey', 3.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Offense']
    },
    {
        cardName:"Argivian Avenger",
        power:5,
        toughness:5,
        imageUrl:"/assets/cardImg/argivianAvenger.jpg",
        convertedManaCost:6,
        type:['Artifact', 'Creature'],
        subtype:['Shapeshifter'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Offense']
    },
    {
        cardName:"Callaphe, Beloved of the Sea",
        power:0,
        toughness:3,
        imageUrl:"/assets/cardImg/callaphe,BelovedOfTheSea.jpg",
        convertedManaCost:3,
        type:['Legendary', 'Enchantment', 'Creature'],
        subtype:['Demigod'],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 2.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Control']
    },
    {
        cardName:"Clay Statue",
        power:3,
        toughness:1,
        imageUrl:"/assets/cardImg/clayStatue.jpg",
        convertedManaCost:4,
        type:['Artifact', 'Creature'],
        subtype:['Golem'],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Defense']
    },
    {
        cardName:"Clock of Omens",
        imageUrl:"/assets/cardImg/clockOfOmens.jpg",
        convertedManaCost:4,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Clockwork Beast",
        power:0,
        toughness:4,
        imageUrl:"/assets/cardImg/clockworkBeast.jpg",
        convertedManaCost:6,
        type:['Artifact', 'Creature'],
        subtype:['Beast'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Offense']
    },
    {
        cardName:"Copper Myr",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/copperMyr.jpg",
        convertedManaCost:2,
        type:['Artifact', 'Creature'],
        subtype:['Myr'],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Cradle Clearcutter",
        power:3,
        toughness:6,
        imageUrl:"/assets/cardImg/cradleClearcutter.jpg",
        convertedManaCost:6,
        type:['Artifact', 'Creature'],
        subtype:['Golem'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[["Grey",2], ["Green",1]],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Crystal Rod",
        imageUrl:"/assets/cardImg/crystalRod.jpg",
        convertedManaCost:1,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Demon's Horn",
        imageUrl:"/assets/cardImg/demon'sHorn.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Drafna, Founder of Lat-Nam",
        power:2,
        toughness:1,
        imageUrl:"/assets/cardImg/drafna,FounderOfLat-nam.jpg",
        convertedManaCost:2,
        type:['Legendary', 'Creature'],
        subtype:['Human', 'Artificer', 'Advisor'],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Commander']
    },
    {
        cardName:"Dragon's Claw",
        imageUrl:"/assets/cardImg/dragon'sClaw.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Elixir of Immortality",
        imageUrl:"/assets/cardImg/elixirOfImmortality.jpg",
        convertedManaCost:1,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Forging the Anchor",
        imageUrl:"/assets/cardImg/forgingTheAnchor.jpg",
        convertedManaCost:3,
        type:['Sorcery'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Tutor']
    },
    {
        cardName:"Frogmite",
        power:2,
        toughness:2,
        imageUrl:"/assets/cardImg/frogmite.jpg",
        convertedManaCost:4,
        type:['Artifact', 'Creature'],
        subtype:['Frog'],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Geode Golem",
        power:5,
        toughness:3,
        imageUrl:"/assets/cardImg/geodeGolem.jpg",
        convertedManaCost:5,
        type:['Artifact', 'Creature'],
        subtype:['Golem'],
        cost:[['X', 1], ['Grey', 5.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Tutor']
    },
    {
        cardName:"Gold Myr",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/goldMyr.jpg",
        convertedManaCost:2,
        type:['Artifact', 'Creature'],
        subtype:['Myr'],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Into Thin Air",
        imageUrl:"/assets/cardImg/intoThinAir.jpg",
        convertedManaCost:6,
        type:['Instant'],
        subtype:[],
        cost:[['X', 1], ['Grey', 5.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Iron Myr",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/ironMyr.jpg",
        convertedManaCost:2,
        type:['Artifact', 'Creature'],
        subtype:['Myr'],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Iron Star",
        imageUrl:"/assets/cardImg/ironStar.jpg",
        convertedManaCost:1,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Island",
        imageUrl:"/assets/cardImg/island.jpg",
        convertedManaCost:0,
        type:['Basic', 'Land'],
        subtype:['Island'],
        cost:[['X', 1]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Blue']
    },
    {
        cardName:"Ivory Cup",
        imageUrl:"/assets/cardImg/ivoryCup.jpg",
        convertedManaCost:1,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Jolt",
        imageUrl:"/assets/cardImg/jolt.jpg",
        convertedManaCost:3,
        type:['Instant'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Draw']
    },
    {
        cardName:"Key to the City",
        imageUrl:"/assets/cardImg/keyToTheCity.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Offense']
    },
    {
        cardName:"Kiora's Dambreaker",
        power:5,
        toughness:6,
        imageUrl:"/assets/cardImg/kiora'sDambreaker.jpg",
        convertedManaCost:6,
        type:['Creature'],
        subtype:['Leviathan'],
        cost:[['X', 1], ['Grey', 5.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Proliforate']
    },
    {
        cardName:"Krark-Clan Ironworks",
        imageUrl:"/assets/cardImg/krark-clanIronworks.jpg",
        convertedManaCost:4,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Leaden Myr",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/leadenMyr.jpg",
        convertedManaCost:2,
        type:['Artifact', 'Creature'],
        subtype:['Myr'],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Levitation",
        imageUrl:"/assets/cardImg/levitation.jpg",
        convertedManaCost:4,
        type:['Enchantment'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 2.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Enhance']
    },
    {
        cardName:"Liquimetal Coating",
        imageUrl:"/assets/cardImg/liquimetalCoating.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Littjara Mirrorlake",
        imageUrl:"/assets/cardImg/littjaraMirrorlake.jpg",
        convertedManaCost:0,
        type:['Land'],
        subtype:[],
        cost:[['X', 1]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Blue']
    },
    {
        cardName:"Machinate",
        imageUrl:"/assets/cardImg/machinate.jpg",
        convertedManaCost:3,
        type:['Instant'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 2.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Magnetic Flux",
        imageUrl:"/assets/cardImg/magneticFlux.jpg",
        convertedManaCost:3,
        type:['Instant'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Master Transmuter",
        power:1,
        toughness:2,
        imageUrl:"/assets/cardImg/masterTransmuter.jpg",
        convertedManaCost:4,
        type:['Artifact', 'Creature'],
        subtype:['Human', 'Artificer'],
        cost:[['X', 1], ['Grey', 3.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Meteor Golem",
        power:3,
        toughness:3,
        imageUrl:"/assets/cardImg/meteorGolem.jpg",
        convertedManaCost:7,
        type:['Artifact', 'Creature'],
        subtype:['Golem'],
        cost:[['X', 1], ['Grey', 7.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Remove']
    },
    {
        cardName:"Mirror Shield",
        imageUrl:"/assets/cardImg/mirrorShield.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:['Equipment'],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Enhance']
    },
    {
        cardName:"Ornithopter",
        power:0,
        toughness:2,
        imageUrl:"/assets/cardImg/ornithopter.jpg",
        convertedManaCost:0,
        type:['Artifact', 'Creature'],
        subtype:['Thopter'],
        cost:[['X', 1], ['Grey', 0.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Defense']
    },
    {
        cardName:"Power Sink",
        imageUrl:"/assets/cardImg/powerSink.jpg",
        convertedManaCost:1,
        type:['Instant'],
        subtype:[],
        cost:[['X', 1], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Counter']
    },
    {
        cardName:"Prototype Portal",
        imageUrl:"/assets/cardImg/prototypePortal.jpg",
        convertedManaCost:4,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Token']
    },
    {
        cardName:"Quicksilver Behemoth",
        power:4,
        toughness:5,
        imageUrl:"/assets/cardImg/quicksilverBehemoth.jpg",
        convertedManaCost:7,
        type:['Creature'],
        subtype:['Beast'],
        cost:[['X', 1], ['Grey', 6.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Raiders' Karve",
        power:4,
        toughness:4,
        imageUrl:"/assets/cardImg/raiders'Karve.jpg",
        convertedManaCost:3,
        type:['Artifact'],
        subtype:['Vehicle'],
        cost:[['X', 1], ['Grey', 3.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Ramos, Dragon Engine",
        power:4,
        toughness:4,
        imageUrl:"/assets/cardImg/ramos,DragonEngine.jpg",
        convertedManaCost:6,
        type:['Legendary', 'Artifact', 'Creature'],
        subtype:['Dragon'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Offense']
    },
    {
        cardName:"Razorfield Rhino",
        power:4,
        toughness:4,
        imageUrl:"/assets/cardImg/razorfieldRhino.jpg",
        convertedManaCost:6,
        type:['Artifact', 'Creature'],
        subtype:['Rhino'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Reconstruction",
        imageUrl:"/assets/cardImg/reconstruction.jpg",
        convertedManaCost:1,
        type:['Instant'],
        subtype:[],
        cost:[['X', 1], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Tutor']
    },
    {
        cardName:"Rootwater Diver",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/rootwaterDiver.jpg",
        convertedManaCost:1,
        type:['Creature'],
        subtype:['Merfolk'],
        cost:[['X', 1], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Tutor']
    },
    {
        cardName:"Rusted Relic",
        imageUrl:"/assets/cardImg/rustedRelic.jpg",
        convertedManaCost:4,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Sandstone Oracle",
        power:4,
        toughness:4,
        imageUrl:"/assets/cardImg/sandstoneOracle.jpg",
        convertedManaCost:7,
        type:['Artifact', 'Creature'],
        subtype:['Sphinx'],
        cost:[['X', 1], ['Grey', 7.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Draw']
    },
    {
        cardName:"Sawtooth Thresher",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/sawtoothThresher.jpg",
        convertedManaCost:6,
        type:['Artifact', 'Creature'],
        subtype:['Construct'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Proliforate']
    },
    {
        cardName:"Scrapdiver Serpent",
        power:5,
        toughness:5,
        imageUrl:"/assets/cardImg/scrapdiverSerpent.jpg",
        convertedManaCost:7,
        type:['Creature'],
        subtype:['Serpent'],
        cost:[['X', 1], ['Grey', 5.0], ['Blue', 2.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Offense']
    },
    {
        cardName:"Screeching Silcaw",
        power:1,
        toughness:2,
        imageUrl:"/assets/cardImg/screechingSilcaw.jpg",
        convertedManaCost:2,
        type:['Creature'],
        subtype:['Bird'],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Sculpting Steel",
        imageUrl:"/assets/cardImg/sculptingSteel.jpg",
        convertedManaCost:3,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 3.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Silver Myr",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/silverMyr.jpg",
        convertedManaCost:2,
        type:['Artifact', 'Creature'],
        subtype:['Myr'],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Skitterbeam Battalion",
        power:4,
        toughness:4,
        imageUrl:"/assets/cardImg/skitterbeamBattalion.jpg",
        convertedManaCost:9,
        type:['Artifact', 'Creature'],
        subtype:['Construct'],
        cost:[['X', 1], ['Grey', 9.0]],
        optional:[["Grey",3], ["Red",2]],
        color:["['Colorless']"],
        purpose:['Token']
    },
    {
        cardName:"Skyclave Sentinel",
        power:2,
        toughness:3,
        imageUrl:"/assets/cardImg/skyclaveSentinel.jpg",
        convertedManaCost:3,
        type:['Artifact', 'Creature'],
        subtype:['Gargoyle'],
        cost:[['X', 1], ['Grey', 3.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Offense']
    },
    {
        cardName:"Skystrike Officer",
        power:2,
        toughness:3,
        imageUrl:"/assets/cardImg/skystrikeOfficer.jpg",
        convertedManaCost:3,
        type:['Creature'],
        subtype:['Human', 'Soldier'],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Slagstone Refinery",
        imageUrl:"/assets/cardImg/slagstoneRefinery.jpg",
        convertedManaCost:4,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 4.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Mana']
    },
    {
        cardName:"Soaring Seacliff",
        imageUrl:"/assets/cardImg/soaringSeacliff.jpg",
        convertedManaCost:0,
        type:['Land'],
        subtype:[],
        cost:[['X', 1]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Blue']
    },
    {
        cardName:"Spire Serpent",
        power:3,
        toughness:5,
        imageUrl:"/assets/cardImg/spireSerpent.jpg",
        convertedManaCost:5,
        type:['Creature'],
        subtype:['Serpent'],
        cost:[['X', 1], ['Grey', 4.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Spotter Thopter",
        power:4,
        toughness:5,
        imageUrl:"/assets/cardImg/spotterThopter.jpg",
        convertedManaCost:8,
        type:['Artifact', 'Creature'],
        subtype:['Thopter'],
        cost:[['X', 1], ['Grey', 8.0]],
        optional:[["Grey",3], ["Blue",1]],
        color:["['Colorless']"],
        purpose:['Offense']
    },
    {
        cardName:"Staunch Throneguard",
        power:2,
        toughness:5,
        imageUrl:"/assets/cardImg/staunchThroneguard.jpg",
        convertedManaCost:5,
        type:['Artifact', 'Creature'],
        subtype:['Construct'],
        cost:[['X', 1], ['Grey', 5.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Defense']
    },
    {
        cardName:"Steal Artifact",
        imageUrl:"/assets/cardImg/stealArtifact.jpg",
        convertedManaCost:4,
        type:['Enchantment'],
        subtype:['Aura'],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 2.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Control']
    },
    {
        cardName:"Tamiyo's Immobilizer",
        imageUrl:"/assets/cardImg/tamiyo'sImmobilizer.jpg",
        convertedManaCost:4,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 3.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Tamiyo's Logbook",
        imageUrl:"/assets/cardImg/tamiyo'sLogbook.jpg",
        convertedManaCost:3,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Defense']
    },
    {
        cardName:"Tawnos, Solemn Survivor",
        power:1,
        toughness:3,
        imageUrl:"/assets/cardImg/tawnos,SolemnSurvivor.jpg",
        convertedManaCost:2,
        type:['Legendary', 'Creature'],
        subtype:['Human', 'Artificer'],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Token']
    },
    {
        cardName:"Temple of the False God",
        imageUrl:"/assets/cardImg/templeOfTheFalseGod.jpg",
        convertedManaCost:0,
        type:['Land'],
        subtype:[],
        cost:[['X', 1]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Null']
    },
    {
        cardName:"Thopter Assembly",
        power:5,
        toughness:5,
        imageUrl:"/assets/cardImg/thopterAssembly.jpg",
        convertedManaCost:6,
        type:['Artifact', 'Creature'],
        subtype:['Thopter'],
        cost:[['X', 1], ['Grey', 6.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Token']
    },
    {
        cardName:"Thopter Mechanic",
        power:2,
        toughness:1,
        imageUrl:"/assets/cardImg/thopterMechanic.jpg",
        convertedManaCost:2,
        type:['Creature'],
        subtype:['Human', 'Artificer'],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Thoughtcast",
        imageUrl:"/assets/cardImg/thoughtcast.jpg",
        convertedManaCost:5,
        type:['Sorcery'],
        subtype:[],
        cost:[['X', 1], ['Grey', 4.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Throne of Geth",
        imageUrl:"/assets/cardImg/throneOfGeth.jpg",
        convertedManaCost:2,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 2.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Proliforate']
    },
    {
        cardName:"Tooth of Chiss-Goria",
        imageUrl:"/assets/cardImg/toothOfChiss-goria.jpg",
        convertedManaCost:3,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 3.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Metalcraft']
    },
    {
        cardName:"Transmogrifying Licid",
        power:2,
        toughness:2,
        imageUrl:"/assets/cardImg/transmogrifyingLicid.jpg",
        convertedManaCost:3,
        type:['Artifact', 'Creature'],
        subtype:['Licid'],
        cost:[['X', 1], ['Grey', 3.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Enhance']
    },
    {
        cardName:"Trinket Mage",
        power:2,
        toughness:2,
        imageUrl:"/assets/cardImg/trinketMage.jpg",
        convertedManaCost:3,
        type:['Creature'],
        subtype:['Human', 'Wizard'],
        cost:[['X', 1], ['Grey', 2.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Tutor']
    },
    {
        cardName:"Unknown Shores",
        imageUrl:"/assets/cardImg/unknownShores.jpg",
        convertedManaCost:0,
        type:['Land'],
        subtype:[],
        cost:[['X', 1]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Null']
    },
    {
        cardName:"Vedalken Engineer",
        power:1,
        toughness:1,
        imageUrl:"/assets/cardImg/vedalkenEngineer.jpg",
        convertedManaCost:2,
        type:['Creature'],
        subtype:['Vedalken', 'Artificer'],
        cost:[['X', 1], ['Grey', 1.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Mana']
    },
    {
        cardName:"Witch's Oven",
        imageUrl:"/assets/cardImg/witch'sOven.jpg",
        convertedManaCost:1,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Wooden Sphere",
        imageUrl:"/assets/cardImg/woodenSphere.jpg",
        convertedManaCost:1,
        type:['Artifact'],
        subtype:[],
        cost:[['X', 1], ['Grey', 1.0]],
        optional:[],
        color:["['Colorless']"],
        purpose:['Life']
    },
    {
        cardName:"Workshop Elders",
        power:4,
        toughness:4,
        imageUrl:"/assets/cardImg/workshopElders.jpg",
        convertedManaCost:7,
        type:['Creature'],
        subtype:['Human', 'Artificer'],
        cost:[['X', 1], ['Grey', 6.0], ['Blue', 1.0]],
        optional:[],
        color:["['Blue']"],
        purpose:['Metalcraft']
    },
    
]